### ISSUE TITLE
 CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [ankit6889/tea_cozy#3]
https://github.com/ankit6889/tea_cozy/blob/master/resources/css/style.css#L1-L130

Your CSS is short, clean and succinct -- make sure to keep it up! An area of improvement is to make sure to comment your main stylings so that it's clear why you're styling elements a particular way. Here is a quick reminder on commenting in CSS:

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/39901862-152baab0-5499-11e8-9903-4468a850cfae.png">

**Comment by ankit6889** [comment]
will do that in future
